name:                ride-servant
version:             0.1.0.0
github:              "githubuser/test"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files- it is
# common to point users to the README.md file.
# base >= 4.7 && < 5
description:         Please see the README on GitHub at <https://github.com/githubuser/test#readme>

dependencies:
- base-noprelude
- classy-prelude
- bytestring
- utf8-string
- text
- uuid
- time
- cookie
- bcrypt
- mtl
- containers
- unordered-containers
- transformers
- aeson
- validation
- servant
- servant-server
- servant-auth
- servant-auth-server
- wai
- wai-logger
- warp
- resource-pool
- postgresql-simple
- postgresql-simple-migration

library:
  source-dirs: src

executables:
  ride-servant-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ride-servant

tests:
  ride-servant-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ride-servant
